### ISSUE TITLE
Validation on work metadata form

### ISSUE THREAD

**Issue by eddierubeiz** [sciencehistory/chf-sufia#1110]
This "parent" issue groups a number of related "child" issues, all having to do with the the open-ended project of adding more automatic checks (both server-side and client-side) to metadata before it's accepted into the entry form. ( /works/new and /concern/generic_works/WORK_ID/edit ) . Few such checks are currently in place.

For instance, we may want to enforce the rule that a work can't be marked public unless it has a rights statement. (See e.g. https://github.com/sciencehistory/chf-sufia/pull/1106 for a client-side fix for this).

This work will become more urgent once we have more people entering metadata, but for now this is going in the backlog.

**Comment by jrochkind** [comment]
We already have quite a few issues filed on this. 

Including
#137 
#105 
#104 
#102 
#101 
#100 
#98 
#96 
#26 
#4 

Is it useful for us to have this additional ticket as a 'master' one?  Not sure. 

The general issue is not limited to the "work metadata form", but to data integrity regardless of how it gets into the system (for instance, via the batch create for as well).

**Comment by jrochkind** [comment]
#26 in particular is a superset of the "make sure certain fields are there when a work is made public" issue. 

Quite a lot of stuff was entered, before I even got here, by Anna and Michelle, on this topic. Let's try to make sure we're using what we've already got and not duplicating the work or the recording of it.

**Comment by jrochkind** [comment]
@HKativa I'd suggest you might want to review the existing tickets we have on validation (above, or can be found by just be searching issues for 'validation') for context on what thinking was done on this before, to help determine our priorities going forward. 

If some of those existing tickets (some of which date back to the earliest states of the project) are no longer things we would ever consider doing, we could close them and not have them cluttering up our issue list. 

Otherwise, they could possibly serve as helpful delineating of different validation-related work we could do, so you can see how it fits together, and decide which should be prioritized first.

**Comment by eddierubeiz** [comment]
I'm closing this issue as it seems to be an obvious duplicate of #102. -- an "umbrella" issue covering tickets that have to do with validation. See also the label https://github.com/sciencehistory/chf-sufia/labels/validation .
