### ISSUE TITLE
Create admin page to monitor fixity logs and checksums

### ISSUE THREAD

**Issue by hackmastera** [sciencehistory/chf-sufia#6]

**Comment by hackmastera** [comment]
relevant, in-progress: https://github.com/projecthydra/sufia/pull/1181/files

**Comment by jrochkind** [comment]
would want some specs on what we'd want here. Just failing fixity checks? (which will usually be zero).  Interactive ability to look up fixity checks on things to confirm when they last happened etc? Other? 

Should think in terms of our staff use cases, what we need/want/will use this information for.

**Comment by MDiMeo** [comment]
This first came up years ago when I was completing my digital curation certificate. As part of that class, we were testing various preservation software packages and these dashboards often had a way to check fixity. I remember taking screenshots, but we weren't sharing stuff like that in GitHub tickets back then. Let me do some digging...

But in the meantime, my use case is that I would like a place where I could glance at recent fixity checks and clearly see that they had all passed. I would imagine that a report would be generated automatically and that this would just be a place where I could glance and make sure that fixity checks were running and passing. If something failed, it would be flagged up in a really obvious way in the UI and, in an ideal world, I would have also gotten an email (which would prompt me to go on here.) I would want to see the object number  and when it failed so that I could talk to @sanfordd about locating a back-up.

**Comment by jrochkind** [comment]
There isn't really a "report" generated, there's just a database of all the recent fixity checks (we can configure how recent we keep, but it doesn't keep them all forever to avoid filling up the db).  and their statuses.  

I'm thinking the 'dashboard' kind of is the report, and should probably a) Definitely tell you if there are any failures, with detials, b) give some kind of summary information about how many fixity checks have been run recently, to keep you confident that fixity checks are happening. 

You can already navigate to an individual file 'info' page to find out when the most recent fixity check was run on it, and it's status.

**Comment by jrochkind** [comment]
hmm, maybe also ideally information on the files that have currently gone longest without a fixity check... but that's pretty hard to figure out from the sufia data model, alas.

**Comment by MDiMeo** [comment]
Yes, this all sounds like it's in line with my thinking. I remember that one of the systems I tried had allowed me to enter date limits and it generated a rather unwieldy spreadsheet (for example, all fixity checks run over the past month.) I'm not sure I can think of a use case for this though.

It would be nice to know which has gone the longest without a fixity check. Or some way to generate a query to see what hasn't been checked for [xx] months. But I think of this as a bonus feature. I'm mostly concerned with points A and B in your comment, above.

**Comment by eddierubeiz** [comment]
Closing this issue, although we can of course adjust the page as needed.
