### ISSUE TITLE
Make viewer page print-friendly

### ISSUE THREAD

**Issue by hackmastera** [sciencehistory/chf-sufia#795]

**Comment by MDiMeo** [comment]
I rewatched the screencasts. Two users were in the image viewer and tried to print. One looked for a button and one just right-clicked and selected print from the pop-up menu. When the other user couldn't find a button they selected print from the tool icon on the top right of the IE browser. In both cases the image was stretched in a funny way and was overlain over some text, making it unusable.

**Comment by jrochkind** [comment]
I think this is probably related to derivatives/#635 , in that an actual good printable page is probably going to be one with a page-sized JPG on it.

**Comment by jrochkind** [comment]
Although I guess there's a question about what users want to print. The entire page they are currently looking at?  Just the part that they have currently zoomed into?  All pages for multi-page works?  We could spend more time and support options for all of these, or we could start by trying to identify the most common use case and focusing on that, for less development time.

**Comment by MDiMeo** [comment]
With these two users, one was trying to print an image of a microscope and one wanted one page of the Newton manuscript. Neither mentioned the need to print a zoomed in version, but of course our deep zoom wasn't working well in the user testing. I think they just wanted to print the single image they were looking at so that it didn't look stretched in a strange way or overlain on other background text.

Unrelated to user testing, but two researchers have told me they like printing entire books from digital collections so they can keep a bound copy on their bookshelf. However, if we're eventually going to give the option of downloading a PDF of the whole item, then I wonder if we don't need to include this print option in the image viewer -- they can download the PDF and print from there.

**Comment by jrochkind** [comment]
That's true of single page too though, right?  They could download the TIFF and/or the full-res JPG and just print that. Probably the full-res JPG is fine for the resolution you'd get in a single-page printout. 

In either case, creating those derivatives is, I think, the first steps for providing print functionality, and a blocker for it. First we'd have to _have_ a full-res JPG or a PDF avail for download, then after we do that, if people still need a print function, we can create one that prints those things for you. But we have to have em to print before we can make a function to print em. :)

**Comment by jrochkind** [comment]
reference on resolutions needed for various printing sizes. http://www.urban75.org/photos/print.html

**Comment by MDiMeo** [comment]
Need to speak with more users about what they're expecting to get when they try to print from image viewer.

**Comment by MDiMeo** [comment]
Notes from user testing on 2/7/2018:
- 2/3 users said they wouldn't try to print from the image viewer or show page. If they needed to print, they would download the image and print that.
- If there was a print button in the image viewer, 3/3 users said they would expect it to fit the image to the page and print. No one expected it to print a zoomed in version.
- 1 user said they could imagine printing images and using them in a brainstorming exercise. They would try to print from the show page and would like the title and URL printed with the large thumbnail so they  could remember where it came from. They wouldn't necessarily need all the metadata for this exercise, but they could imagine wanting it for other situations.
- The usefulness of a PDF came up casually in conversation with 2 users.

**Comment by HKativa** [comment]
Closing ticket since this issue and potential use cases are addressed by implementation of PDF and ZIP downloads (see #710).
