### ISSUE TITLE
Individual user account permission errors

### ISSUE THREAD

**Issue by sanfordd** [sciencehistory/chf-sufia#988]
Using the individual user accounts has encountered some issues that the general deployment account does not have. Collect the problems here.

**Comment by jrochkind** [comment]
If I try running a rake task as `jrochkind`, I get: `Rails Error: Unable to access log file. Please ensure that /opt/sufia-project/releases/20180220164136/log/production.log exists and is writable (ie, make it writable for user and group: chmod 0664 /opt/sufia-project/releases/20180220164136/log/production.log). The log level has been raised to WARN and the output directed to STDERR until the problem is fixed.`

**Comment by jrochkind** [comment]
succesfully ran a rake task, looks good. Can file new issue if other barriers arise.

**Comment by sanfordd** [comment]
Sounds good.
