### ISSUE TITLE
Managing works that are PDFs

### ISSUE THREAD

**Issue by MDiMeo** [sciencehistory/chf-sufia#994]
Our first PDF use case is to include the [Neville rare book catalog](http://othmerlib.chemheritage.org/search~S6?/Xneville+catalog&searchscope=6&SORT=D/Xneville+catalog&searchscope=6&SORT=D&SUBKEY=neville+catalog/1%2C7%2C7%2CB/frameset&FF=Xneville+catalog&searchscope=6&SORT=D&1%2C1%2C) in the Digital Collections. Jim is hoping that the text will be indexed by Google. He would like people to be able to download the PDF and perhaps view it in their browser. We understand that it won't work with our current image viewer.

- [x] Thumbnail logic needs review/feedback possibly (or not) including from stakeholders and/or users
    * decided current first page of PDF is good enough for now, Neville catalog will have new title pages created. 

## Maybe:

- ( ) re-enable zip download for multi-item works including pdfs *(not for now, we might not have lots of multi-PDF things)*

- [x] add page count in download links for PDFs? YES

- [x] Should the fact that the original is a PDF (and it's page count) be displayed somewhere else on page? YES, add file type to metadata

- [x] Make sure PDF originals are in index XML files given to google/google images? (yes)

- ( ) Neville Catalog PDF is really large file size; spend time figuring out why and if it can be reduced? *(will handle later, doesn't need to hold up this pr)*

**Comment by jrochkind** [comment]
@MDiMeo do you know what's behind the choice to split that up into two PDFs at present?

**Comment by jrochkind** [comment]
ah, nevermind, I see, it's two physical volumes.

**Comment by HKativa** [comment]
Additional use case based on conversation with Lee Berry re integrating select oral histories into the digital collections in some capacity: We agreed that adding oral histories to the collection is dependent upon the records including a deliverable that users can access directly through our site (we don't want metadata records that send users somewhere else, as the existing oral histories microsite does now). In all likelihood, that deliverable would be a PDF transcript, rather than sound or video files. Lee is going to follow up re how many oral histories they can make freely available, based on permissions, etc., and we can continue the conversation from there.

**Comment by jrochkind** [comment]
The use case I'm going to focus on initially is a work that is _only_ PDFs. 

The code may not work for "works" that are composed of both TIFFs and PDFs. At the moment I'm not considering that in-scope, but that can be changed, if you know different now, or based on testing or experience later.

**Comment by jrochkind** [comment]
Of the links [above](https://github.com/sciencehistory/chf-sufia/issues/994#issuecomment-368570267) to the two PDFs for our initial use case, only the second one still works. 

I'm not sure where these came from initially. Jim? Can someoen (@HKativa ?) try to re-acquire the volume 1 PDF so I can use it as a sample? Thanks!

**Comment by jrochkind** [comment]
When downloading an original file, the logic we already had for creating filenames for our other derivative downloads is now being used. 

This means the file ID is included in the download name, for better matching to our system. 

It unfortunately does not mean you actually get words from the work title in there, because of the way the stack download action worked that wasn't feasible. 

It does mean that periods are replaced by underscores. 

So for an existing example, the download from https://digital.sciencehistory.org/works/2f75r844w _was_ filename `2008.064_027.tif`, it is now `2008_064_027_6t053g416.tiff`.

Please let me know if this will cause any problems, I can put it back to what it was. Just was working on the code for PDF downloads and had to do some edits in relevant places, and at first I thought I _had_ to make this change -- I don't really though.

**Comment by jrochkind** [comment]
The two neville catalog PDFs both have the same first page, so both have identical thumbs. I can't demo this at the moment, cause I don't have access to the first one. 

Additionally, they are white pages with just a little bit of text on them, so look a bit weird as "thumbnails". See https://staging.digital.sciencehistory.org/works/x346d520z

We could have the PDF thumbnail generation add a thin border around the thumbs if we wanted. It would be for all thumbs, even ones that don't need it, but I suspect that won't hurt much.

**Comment by jrochkind** [comment]
So Neville Catalog PDF is available as a demo in staging (need to be logged in to see it).

You’ll see it is in two PDFs for two volumes. At present the software is using the first page of PDF as thumb, and they both have the same (not very informative or attractive) first page, so they are kind of indistinguishable. :disappointed:

https://staging.digital.sciencehistory.org/works/x346d520z

You'll note that "download" option forces download to your local computer, while "view" option just results in viewing the PDF in browser. 

Q’s for consideration:

1. Can we alter these PDFs to have better/more distinct first pages (for instance, the more complete title pages which is in both volumes), or do we need a feature to allow staff to choose page for thumb (kind of painful to implement), or neither?

2. The plain white pages end up looking a bit weird/confusing when used as thumbs, as they blend into our white bg. Perhaps the PDF thumb generation should put a small border around the thumbs, since PDFs are likely to be plain white pages?

**Comment by jrochkind** [comment]
All PDF thumbnail options I can think of, some trickier to implement than others:

1. make thumbnail of first page
2. allow staff to specify a page to make thumbnail of
3. don't use a thumbnail at all for PDFs
4. Use a generic "PDF" thumbnail for PDFs
5. Use a generic PDF thumbnail with title (or as much as title as fits) superimposed
6. allow staff to upload some separate image to use as thumbnail. 
7. staff-configuration to do some of these things with some pdfs and others with others

Depending on what we choose, we may have to see what we want to send as a thumb to DPLA.

**Comment by HKativa** [comment]
On 7/23/2018, I met with our two current PDF stakeholders, Lee (Oral Histories) and Jim (Neville catalog). With regards to the thumbnails, both felt that using the first page as a thumbnail is sufficient. In the case of the oral histories, the title pages are all standardized with basic metadata that meets our needs. In the case of the Neville catalog, Jim favored editing the PDFs to produce a descriptive title page more to our liking rather than implementing any of the alternative functionalities. In the absence of other PDF use cases, adapting the Neville catalog accordingly seems like the way to go.

**Comment by jrochkind** [comment]
initial implementation merged as per discussion with @HKativa . More work can be done in future, as experience and user analysis guides, we can open up new Issues then if needed.
